In [1]:
import pandas as pd

In [2]:
i=pd.read_csv("iphone_purchase_records.csv")
i

Gender  Age  Salary  Purchase Iphone
0      Male   19   19000                0
1      Male   35   20000                0
2    Female   26   43000                0
3    Female   27   57000                0
4      Male   19   76000                0
..      ...  ...     ...              ...
395  Female   46   41000                1
396    Male   51   23000                1
397  Female   50   20000                1
398    Male   36   33000                0
399  Female   49   36000                1

[400 rows x 4 columns]

In [3]:
i.isnull().sum()

Gender             0
Age                0
Salary             0
Purchase Iphone    0
dtype: int64

In [4]:
i.describe()

Age         Salary  Purchase Iphone
count  400.000000     400.000000       400.000000
mean    37.655000   69742.500000         0.357500
std     10.482877   34096.960282         0.479864
min     18.000000   15000.000000         0.000000
25%     29.750000   43000.000000         0.000000
50%     37.000000   70000.000000         0.000000
75%     46.000000   88000.000000         1.000000
max     60.000000  150000.000000         1.000000

In [5]:
i.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64 
 2   Salary           400 non-null    int64 
 3   Purchase Iphone  400 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 12.6+ KB


In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
l=LabelEncoder()
i['Gender']=l.fit_transform(i['Gender'])
i['Gender']

0      1
1      1
2      0
3      0
4      1
      ..
395    0
396    1
397    0
398    1
399    0
Name: Gender, Length: 400, dtype: int64

In [8]:
i

Gender  Age  Salary  Purchase Iphone
0         1   19   19000                0
1         1   35   20000                0
2         0   26   43000                0
3         0   27   57000                0
4         1   19   76000                0
..      ...  ...     ...              ...
395       0   46   41000                1
396       1   51   23000                1
397       0   50   20000                1
398       1   36   33000                0
399       0   49   36000                1

[400 rows x 4 columns]

In [9]:
x=i[["Gender","Age","Salary"]]
y=i["Purchase Iphone"]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [11]:
x_train

Gender  Age  Salary
247       0   57  122000
110       0   39   71000
16        1   47   25000
66        1   24   19000
153       0   36   50000
..      ...  ...     ...
71        0   24   27000
106       0   26   35000
270       0   43  133000
348       1   39   77000
102       0   32   86000

[300 rows x 3 columns]

In [12]:
#from sklearn.preprocessing import MinMaxScaler

In [13]:
# m=MinMaxScaler()
# mx_train=m.fit_transform(x_train)
# mx_train

In [14]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
sx_train=s.fit_transform(x_train)
sx_train

array([[-0.98675438,  1.8925893 ,  1.52189404],
       [-0.98675438,  0.1250379 ,  0.03213212],
       [ 1.01342342,  0.9106163 , -1.31157471],
       [ 1.01342342, -1.34792161, -1.48684082],
       [-0.98675438, -0.169554  , -0.58129926],
       [-0.98675438, -0.56234321,  2.33980255],
       [-0.98675438,  1.0088136 , -1.19473064],
       [ 1.01342342, -0.75873781,  1.08372877],
       [ 1.01342342,  2.1871812 , -1.04867555],
       [ 1.01342342,  0.0268406 , -0.25997806],
       [ 1.01342342, -0.46414591, -1.1363086 ],
       [ 1.01342342,  0.1250379 ,  0.03213212],
       [ 1.01342342,  1.6961947 , -0.90262046],
       [-0.98675438,  1.1070109 , -0.90262046],
       [-0.98675438,  0.5178271 ,  1.22978386],
       [ 1.01342342, -1.05332971, -1.4576298 ],
       [-0.98675438, -1.15152701, -1.54526286],
       [-0.98675438, -0.0713567 ,  0.67477452],
       [ 1.01342342,  0.4196298 , -0.46445519],
       [ 1.01342342, -0.2677513 , -0.25997806],
       [ 1.01342342, -0.85693511,  0.148

In [15]:
sx_test=s.transform(x_test)
sx_test

array([[-0.98675438,  0.812419  , -1.39920777],
       [-0.98675438,  2.0889839 ,  0.52871943],
       [-0.98675438, -0.95513241, -0.75656537],
       [-0.98675438,  1.0088136 ,  0.76240757],
       [-0.98675438, -0.85693511, -1.22394166],
       [-0.98675438, -0.75873781, -0.23076704],
       [-0.98675438,  0.9106163 ,  1.08372877],
       [-0.98675438, -0.85693511,  0.38266434],
       [ 1.01342342,  0.2232352 ,  0.14897619],
       [ 1.01342342,  0.4196298 , -0.14313399],
       [-0.98675438, -0.2677513 , -0.14313399],
       [-0.98675438,  1.4998001 , -1.04867555],
       [-0.98675438, -1.44611891, -0.6397213 ],
       [-0.98675438, -1.74071081, -1.36999675],
       [ 1.01342342, -0.75873781,  0.49950841],
       [ 1.01342342, -0.2677513 ,  1.11293979],
       [-0.98675438,  1.4016028 , -0.93183148],
       [-0.98675438,  0.812419  ,  0.11976517],
       [ 1.01342342,  0.1250379 , -0.8149874 ],
       [ 1.01342342,  1.794392  , -0.28918908],
       [-0.98675438, -1.54431621, -1.253

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
kn=KNeighborsClassifier(n_neighbors=5,metric="euclidean")
kn.fit(sx_train,y_train)

KNeighborsClassifier(metric='euclidean')

In [18]:
y_pred=kn.predict(sx_test)
y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [20]:
accuracy_score(y_pred,y_test)

0.92

In [21]:
confusion_matrix(y_test,y_pred)

array([[58,  5],
       [ 3, 34]])

In [22]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.95      0.92      0.94        63\n           1       0.87      0.92      0.89        37\n\n    accuracy                           0.92       100\n   macro avg       0.91      0.92      0.92       100\nweighted avg       0.92      0.92      0.92       100\n'

In [23]:
mi=s.transform([[1,35,100000]])
mip=kn.predict(mi)
mip

C:\Users\Livewire\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1])

In [24]:
# import numpy as np
# sso=np.array([[-1.        , -1.06675246, -0.38634438],
#        [ 1.        ,  0.79753468, -1.22993871],
#        [-1.        ,  0.11069205,  1.853544  ],
#        [-1.        ,  0.60129393, -0.90995465],
#        [-1.        ,  1.87685881, -1.28811763],
#        [ 1.        , -0.57615058,  1.44629156],
#        [ 1.        ,  0.3069328 , -0.53179168],
#        [ 1.        ,  0.99377543,  0.10817643],
#        [ 1.        , -1.16487283,  0.45724994],
#        [ 1.        , -1.55735433,  0.31180264],
#        [ 1.        ,  1.0918958 ,  0.45724994],
#        [-1.        , -0.18366908, -0.47361276],
#        [ 1.        ,  0.20881242, -0.32816546],
#        [-1.        ,  0.3069328 ,  0.28271318],
#        [ 1.        , -1.16487283, -1.57901222],
#        [-1.        ,  0.11069205,  0.25362372],
#        [ 1.        ,  2.07309956,  1.73718616],
#        [ 1.        ,  0.40505317, -0.18271817],
#        [-1.        ,  1.4843773 ,  2.11534913],
#        [ 1.        , -0.37990983,  1.21357589],
#        [-1.        ,  1.87685881,  1.50447048],
#        [-1.        ,  0.11069205,  0.02090805],
#        [ 1.        ,  0.89565505, -1.31720709],
#        [ 1.        , -1.36111358, -1.49174384],
#        [-1.        , -0.18366908, -0.5899706 ],
#        [-1.        , -0.57615058,  2.31897535],
#        [-1.        ,  0.99377543, -1.20084925],
#        [ 1.        , -0.77239133,  1.06812859],
#        [ 1.        ,  2.17121993, -1.05540195],
#        [ 1.        ,  0.01257167, -0.26998655],
#        [ 1.        , -0.4780302 , -1.14267033],
#        [ 1.        ,  0.11069205,  0.02090805],
#        [ 1.        ,  1.68061805, -0.90995465],
#        [-1.        ,  1.0918958 , -0.90995465],
#        [-1.        ,  0.50317355,  1.21357589],
#        [ 1.        , -1.06675246, -1.46265438],
#        [-1.        , -1.16487283, -1.54992276],
#        [-1.        , -0.0855487 ,  0.66087616],
#        [ 1.        ,  0.40505317, -0.47361276],
#        [ 1.        , -0.28178945, -0.26998655],
#        [ 1.        , -0.87051171,  0.13726589],
#        [-1.        ,  0.01257167,  0.28271318],
#        [ 1.        ,  0.6994143 , -1.28811763],
#        [-1.        ,  1.58249768,  1.09721805],
#        [ 1.        ,  0.79753468, -1.37538601],
#        [-1.        , -1.45923396, -1.22993871],
#        [ 1.        , -0.0855487 ,  0.13726589],
#        [ 1.        ,  0.40505317, -0.15362871],
#        [-1.        , -0.28178945,  0.02090805],
#        [-1.        ,  1.28813655,  2.20261751],
#        [ 1.        ,  0.11069205,  0.74814454],
#        [-1.        , -1.36111358,  0.54451832],
#        [-1.        ,  1.97497918,  0.71905508],
#        [ 1.        , -1.26299321, -1.40447546],
#        [ 1.        ,  0.3069328 , -0.32816546],
#        [ 1.        , -0.96863208,  0.54451832],
#        [-1.        ,  0.40505317,  0.28271318],
#        [-1.        ,  0.40505317,  1.09721805],
#        [-1.        ,  0.79753468,  0.74814454],
#        [-1.        ,  0.89565505,  1.24266535],
#        [-1.        , -0.4780302 , -1.22993871],
#        [ 1.        , -1.85171546, -1.31720709],
#        [ 1.        ,  1.0918958 ,  0.54451832],
#        [-1.        , -0.67427095, -1.60810168],
#        [-1.        , -0.77239133,  0.25362372],
#        [ 1.        ,  0.99377543,  2.05717021],
#        [-1.        , -0.57615058,  1.35902318],
#        [-1.        , -0.0855487 ,  0.02090805],
#        [-1.        , -1.94983583,  0.45724994],
#        [-1.        ,  0.40505317,  0.25362372],
#        [-1.        , -1.06675246,  0.39907102],
#        [ 1.        ,  0.20881242, -0.15362871],
#        [ 1.        ,  1.87685881,  0.10817643],
#        [-1.        , -1.16487283, -1.60810168],
#        [-1.        , -1.16487283,  0.28271318],
#        [ 1.        , -0.87051171, -0.79359682],
#        [-1.        , -0.4780302 ,  2.28988589],
#        [ 1.        ,  0.11069205, -0.82268628],
#        [-1.        ,  1.58249768,  0.98086021],
#        [ 1.        , -0.18366908, -1.08449141],
#        [-1.        ,  0.79753468, -1.11358087],
#        [-1.        ,  0.20881242,  2.08625967],
#        [-1.        , -0.0855487 , -0.24089709],
#        [ 1.        , -0.87051171,  2.26079643],
#        [-1.        , -0.0855487 , -0.38634438],
#        [ 1.        , -0.28178945, -0.5899706 ],
#        [-1.        ,  0.40505317, -0.50270222],
#        [ 1.        , -0.28178945, -0.93904411],
#        [-1.        ,  0.3069328 , -1.17175979],
#        [-1.        ,  0.20881242,  0.04999751],
#        [ 1.        , -1.16487283, -1.60810168],
#        [-1.        , -0.67427095, -0.06636033],
#        [ 1.        , -0.28178945, -0.50270222],
#        [-1.        , -0.28178945, -1.31720709],
#        [ 1.        , -0.77239133,  0.54451832],
#        [ 1.        ,  0.3069328 ,  0.04999751],
#        [ 1.        , -0.96863208,  1.53355994],
#        [-1.        ,  0.79753468,  0.3408921 ],
#        [-1.        , -1.55735433, -0.21180763],
#        [-1.        ,  0.6994143 , -1.40447546],
#        [ 1.        , -0.77239133, -0.61906006],
#        [-1.        , -0.37990983, -1.31720709],
#        [-1.        ,  0.20881242,  0.13726589],
#        [-1.        , -0.57615058,  1.35902318],
#        [-1.        , -1.45923396,  0.3408921 ],
#        [ 1.        , -1.16487283,  0.28271318],
#        [-1.        ,  0.99377543,  1.76627562],
#        [ 1.        ,  2.07309956,  2.11534913],
#        [ 1.        , -0.28178945, -0.4445233 ],
#        [ 1.        , -0.37990983, -0.79359682],
#        [-1.        ,  0.11069205, -0.26998655],
#        [-1.        , -1.06675246,  0.74814454],
#        [ 1.        ,  2.17121993,  0.36998156],
#        [ 1.        , -1.36111358, -0.4445233 ],
#        [ 1.        ,  1.97497918,  2.14443859],
#        [-1.        ,  1.4843773 ,  0.98086021],
#        [ 1.        , -0.28178945,  0.25362372],
#        [ 1.        , -0.18366908,  0.83541291],
#        [ 1.        ,  1.87685881, -0.29907601],
#        [-1.        , -0.0855487 ,  1.94081237],
#        [ 1.        , -0.4780302 , -0.79359682],
#        [-1.        ,  0.3069328 ,  0.02090805],
#        [-1.        ,  1.38625693, -1.43356492],
#        [ 1.        ,  1.38625693,  2.31897535],
#        [ 1.        , -0.0855487 , -0.00818141],
#        [-1.        , -1.16487283,  0.39907102],
#        [-1.        , -1.16487283,  0.04999751],
#        [-1.        , -1.16487283, -0.53179168],
#        [-1.        ,  0.3069328 , -0.29907601],
#        [ 1.        , -0.67427095, -0.12453925],
#        [ 1.        , -0.0855487 ,  2.14443859],
#        [ 1.        ,  0.01257167, -0.26998655],
#        [-1.        , -0.67427095, -1.05540195],
#        [-1.        ,  0.40505317,  0.13726589],
#        [ 1.        ,  0.79753468,  1.35902318],
#        [ 1.        , -0.18366908, -0.53179168],
#        [ 1.        ,  0.01257167,  0.02090805],
#        [ 1.        ,  1.0918958 ,  0.51542886],
#        [-1.        ,  1.87685881, -1.08449141],
#        [-1.        ,  0.99377543,  1.96990183],
#        [-1.        ,  0.89565505, -0.5899706 ],
#        [-1.        , -0.4780302 , -0.03727087],
#        [-1.        , -0.0855487 ,  2.20261751],
#        [-1.        , -1.75359508,  0.3408921 ],
#        [ 1.        ,  0.20881242, -0.67723898],
#        [ 1.        , -0.28178945, -1.40447546],
#        [-1.        , -1.75359508, -0.99722303],
#        [-1.        ,  0.6994143 , -0.7354179 ],
#        [-1.        , -1.16487283, -0.79359682],
#        [-1.        ,  1.97497918,  0.89359183],
#        [ 1.        ,  0.20881242, -0.38634438],
#        [-1.        ,  0.01257167,  1.21357589],
#        [-1.        , -0.0855487 ,  0.28271318],
#        [ 1.        ,  1.0918958 , -1.22993871],
#        [-1.        , -0.18366908,  0.13726589],
#        [-1.        ,  0.3069328 ,  0.04999751],
#        [-1.        , -0.28178945, -0.29907601],
#        [ 1.        ,  0.50317355,  1.7080967 ],
#        [ 1.        ,  0.3069328 ,  0.4863394 ],
#        [-1.        ,  0.01257167,  1.24266535],
#        [-1.        ,  1.97497918, -1.37538601],
#        [ 1.        , -1.16487283, -1.11358087],
#        [ 1.        , -0.57615058, -1.5208333 ],
#        [ 1.        ,  0.3069328 , -0.53179168],
#        [ 1.        , -0.67427095, -1.5208333 ],
#        [ 1.        , -0.28178945,  0.51542886],
#        [-1.        ,  0.99377543, -1.02631249],
#        [ 1.        , -1.06675246,  0.54451832],
#        [-1.        , -0.28178945,  0.777234  ],
#        [ 1.        ,  0.40505317,  0.07908697],
#        [-1.        , -1.65547471, -0.06636033],
#        [-1.        ,  0.3069328 ,  0.04999751],
#        [-1.        , -0.4780302 , -0.29907601],
#        [ 1.        ,  0.11069205,  1.853544  ],
#        [-1.        , -0.96863208,  0.39907102],
#        [ 1.        ,  0.79753468,  0.51542886],
#        [ 1.        , -1.36111358, -0.35725492],
#        [-1.        , -0.67427095,  1.38811264],
#        [-1.        ,  1.19001618,  0.51542886],
#        [-1.        , -1.75359508,  0.3408921 ],
#        [-1.        , -0.57615058,  1.88263345],
#        [ 1.        , -1.75359508,  0.45724994],
#        [ 1.        , -0.28178945, -1.25902817],
#        [ 1.        , -0.87051171, -0.79359682],
#        [ 1.        , -1.65547471,  0.51542886],
#        [ 1.        , -0.28178945, -0.32816546],
#        [ 1.        ,  0.6994143 , -1.11358087],
#        [ 1.        ,  2.17121993, -0.82268628],
#        [ 1.        , -0.28178945,  0.60269724],
#        [-1.        , -0.28178945, -0.76450736],
#        [-1.        , -1.94983583, -0.76450736],
#        [ 1.        ,  0.40505317,  2.28988589],
#        [ 1.        ,  0.6994143 ,  0.25362372],
#        [-1.        ,  0.20881242, -0.29907601],
#        [ 1.        , -1.36111358, -1.37538601],
#        [-1.        , -0.4780302 , -0.56088114],
#        [-1.        ,  0.40505317, -0.00818141],
#        [-1.        ,  1.68061805,  1.73718616],
#        [-1.        ,  1.19001618, -0.76450736],
#        [-1.        ,  0.99377543,  1.4172021 ],
#        [ 1.        , -1.85171546,  0.16635535],
#        [-1.        ,  0.3069328 ,  0.04999751],
#        [ 1.        ,  0.20881242,  0.02090805],
#        [ 1.        , -1.06675246,  0.51542886],
#        [-1.        , -0.18366908,  1.62082832],
#        [ 1.        , -0.28178945,  0.13726589],
#        [ 1.        , -0.28178945, -0.35725492],
#        [ 1.        , -0.37990983,  1.30084427],
#        [ 1.        , -0.28178945,  0.07908697],
#        [-1.        ,  2.17121993,  1.09721805],
#        [ 1.        , -1.26299321,  0.4863394 ],
#        [-1.        , -1.06675246, -0.47361276],
#        [-1.        , -1.65547471, -1.57901222],
#        [ 1.        , -0.0855487 ,  0.10817643],
#        [ 1.        , -0.28178945, -0.90995465],
#        [ 1.        ,  1.58249768, -0.00818141],
#        [-1.        ,  0.89565505, -1.17175979],
#        [-1.        ,  0.01257167, -0.5899706 ],
#        [-1.        , -0.28178945,  2.23170697],
#        [-1.        , -0.28178945,  0.19544481],
#        [ 1.        ,  0.3069328 ,  0.25362372],
#        [-1.        , -0.0855487 , -1.08449141],
#        [-1.        ,  2.17121993, -0.70632844],
#        [-1.        , -0.96863208, -0.32816546],
#        [-1.        , -1.45923396, -0.12453925],
#        [ 1.        , -1.45923396, -0.21180763],
#        [ 1.        , -0.77239133, -1.54992276],
#        [ 1.        , -1.26299321, -1.08449141],
#        [-1.        ,  2.07309956,  0.36998156],
#        [-1.        ,  1.97497918, -0.93904411],
#        [ 1.        , -1.94983583,  0.3408921 ],
#        [ 1.        ,  0.79753468, -0.32816546],
#        [-1.        , -1.06675246, -1.54992276],
#        [-1.        ,  1.97497918, -0.67723898],
#        [-1.        ,  0.99377543, -1.17175979],
#        [ 1.        ,  1.0918958 , -0.15362871],
#        [-1.        ,  1.19001618, -0.99722303],
#        [ 1.        ,  1.4843773 ,  0.04999751],
#        [ 1.        ,  0.20881242, -0.38634438],
#        [-1.        ,  1.38625693,  1.27175481],
#        [-1.        ,  2.07309956, -0.82268628],
#        [-1.        , -0.18366908, -0.21180763],
#        [ 1.        ,  0.40505317,  0.98086021],
#        [ 1.        , -0.0855487 , -0.53179168],
#        [ 1.        ,  0.99377543, -1.08449141],
#        [-1.        ,  2.07309956, -1.20084925],
#        [ 1.        , -0.0855487 ,  0.25362372],
#        [ 1.        ,  0.20881242, -0.26998655],
#        [ 1.        ,  1.0918958 ,  0.10817643],
#        [ 1.        , -1.26299321,  0.57360778],
#        [ 1.        , -0.77239133, -1.60810168],
#        [ 1.        ,  0.20881242,  0.22453427],
#        [ 1.        , -1.36111358,  0.39907102],
#        [-1.        ,  0.01257167, -0.5899706 ],
#        [-1.        ,  0.6994143 ,  1.76627562],
#        [ 1.        , -1.65547471,  0.04999751],
#        [-1.        , -0.28178945, -1.37538601],
#        [ 1.        , -0.28178945, -1.46265438],
#        [-1.        , -0.67427095,  0.54451832],
#        [ 1.        , -0.77239133,  0.28271318],
#        [-1.        ,  0.89565505, -0.67723898],
#        [ 1.        , -1.06675246,  0.57360778],
#        [-1.        , -0.28178945,  0.04999751],
#        [-1.        , -0.77239133,  1.32993372],
#        [ 1.        ,  0.11069205,  1.50447048],
#        [-1.        , -0.87051171,  0.36998156],
#        [-1.        ,  0.3069328 , -0.21180763],
#        [ 1.        ,  0.99377543,  0.57360778],
#        [ 1.        ,  0.01257167, -0.32816546],
#        [ 1.        , -0.57615058, -1.5208333 ],
#        [-1.        ,  0.11069205,  0.13726589],
#        [ 1.        , -1.16487283,  0.31180264],
#        [ 1.        ,  0.11069205,  1.03903913],
#        [-1.        , -1.55735433, -0.4445233 ],
#        [ 1.        , -0.18366908,  1.38811264],
#        [ 1.        ,  2.17121993, -0.82268628],
#        [-1.        , -0.96863208, -0.4445233 ],
#        [-1.        ,  1.28813655,  1.853544  ],
#        [ 1.        ,  1.0918958 , -1.22993871],
#        [ 1.        , -0.18366908, -0.29907601],
#        [-1.        ,  1.77873843,  0.98086021],
#        [-1.        , -1.06675246, -0.35725492],
#        [-1.        , -1.36111358, -1.11358087],
#        [-1.        , -0.37990983,  0.04999751],
#        [ 1.        , -0.96863208, -1.11358087],
#        [-1.        ,  1.19001618, -1.46265438],
#        [-1.        , -0.4780302 , -0.85177573],
#        [-1.        , -0.87051171, -0.67723898],
#        [ 1.        , -1.55735433, -1.5208333 ],
#        [ 1.        , -0.77239133,  1.88263345],
#        [ 1.        ,  0.89565505,  1.00994967],
#        [ 1.        ,  0.79753468,  0.25362372],
#        [-1.        ,  0.99377543,  1.853544  ],
#        [-1.        ,  0.89565505, -0.61906006],
#        [-1.        ,  1.0918958 ,  2.05717021],
#        [ 1.        , -0.57615058,  0.86450237],
#        [ 1.        ,  0.01257167,  0.02090805],
#        [-1.        , -1.85171546, -1.28811763],
#        [ 1.        , -0.0855487 ,  0.19544481],
#        [-1.        ,  0.89565505, -0.56088114],
#        [ 1.        ,  0.20881242, -0.38634438],
#        [ 1.        , -0.18366908,  1.59173886],
#        [ 1.        , -1.75359508,  0.10817643],
#        [ 1.        , -0.67427095, -0.35725492],
#        [ 1.        ,  0.3069328 , -0.7354179 ],
#        [ 1.        ,  0.40505317, -0.47361276],
#        [-1.        , -0.96863208, -0.96813357],
#        [-1.        ,  0.11069205,  0.07908697],
#        [-1.        , -0.96863208,  0.42816048],
#        [ 1.        ,  0.01257167, -0.56088114],
#        [ 1.        ,  0.89565505, -0.79359682],
#        [ 1.        , -0.0855487 ,  0.04999751],
#        [-1.        ,  1.0918958 , -0.99722303],
#        [ 1.        ,  0.6994143 , -1.40447546],
#        [ 1.        , -0.28178945,  0.04999751],
#        [-1.        , -1.36111358, -1.25902817],
#        [-1.        , -1.16487283, -1.02631249],
#        [-1.        ,  0.50317355,  1.82445454],
#        [ 1.        ,  0.11069205,  0.19544481],
#        [-1.        , -0.57615058,  0.45724994]])


In [25]:
#sso.mean()

In [26]:
#sso.std()